services:
  envoy:
    image: envoyproxy/envoy:v1.31-latest
    container_name: envoy

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml

    ports:
      - "10000:10000"
      - "9901:9901"
